"""
Seed all 168 historical places from the Tlemcen PDF inventory into the database.
Run from the backend directory: python seed_places.py
Requires images_result.json (generated by fetch_images.py)
"""

import sys
import os
import json
sys.path.insert(0, os.path.dirname(__file__))

from app import app
from models import db, Place, PlaceTranslation

# ── Load fetched images (1 per place, from Wikimedia Commons) ─────────────────
_images_path = os.path.join(os.path.dirname(__file__), 'images_result.json')
PLACE_PHOTOS: dict[int, str] = {}
if os.path.exists(_images_path):
    with open(_images_path, encoding='utf-8') as _f:
        PLACE_PHOTOS = {int(k): v for k, v in json.load(_f).items()}
    print(f'Loaded {len(PLACE_PHOTOS)} images from images_result.json')
else:
    print('WARNING: images_result.json not found — using category defaults')

# ── Default photos per category (fallback when images_result.json absent) ─────
PHOTO = {
    'geo':             'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Lala_Setti_%D9%84%D8%A7%D9%84%D8%A9_%D8%B3%D8%AA%D9%8A_-_panoramio.jpg/640px-Lala_Setti_%D9%84%D8%A7%D9%84%D8%A9_%D8%B3%D8%AA%D9%8A_-_panoramio.jpg',
    'mosque':          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Grande_Mosqu%C3%A9e_de_Tlemcen.jpg/640px-Grande_Mosqu%C3%A9e_de_Tlemcen.jpg',
    'mausoleum':       'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Porte_de_la_mosqu%C3%A9e_de_Sidi_Boum%C3%A9di%C3%A8ne%2C_Tlemcen.jpg/640px-Porte_de_la_mosqu%C3%A9e_de_Sidi_Boum%C3%A9di%C3%A8ne%2C_Tlemcen.jpg',
    'school':          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Grande_Mosqu%C3%A9e_de_Tlemcen.jpg/640px-Grande_Mosqu%C3%A9e_de_Tlemcen.jpg',
    'civil':           'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Palais_machouar.jpg/640px-Palais_machouar.jpg',
    'military':        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mansourah_Mosque_04.jpg/640px-Mansourah_Mosque_04.jpg',
}

# ── Category → app filter categories ─────────────────────────────────────────
CATS = {
    'geo':       'historic',
    'mosque':    'religious,historic',
    'mausoleum': 'religious',
    'school':    'religious,historic',
    'civil':     'historic',
    'military':  'historic',
}

# ── Badges per type ────────────────────────────────────────────────────────────
BADGE = {
    'geo':       ('أثري',  'Archéologique', 'Archaeological'),
    'mosque':    ('ديني',  'Religieux',     'Religious'),
    'mausoleum': ('ديني',  'Religieux',     'Religious'),
    'school':    ('ديني',  'Religieux',     'Religious'),
    'civil':     ('تاريخي','Historique',    'Historic'),
    'military':  ('تاريخي','Historique',    'Historic'),
}

# ── Description templates per type ────────────────────────────────────────────
DESC = {
    'geo':       ('موقع أثري وجغرافي من التراث الحضاري لمدينة تلمسان.',
                  'Site archéologique et géographique du patrimoine culturel de Tlemcen.',
                  'Archaeological and geographic site of Tlemcen\'s cultural heritage.'),
    'mosque':    ('مسجد تاريخي يعكس روعة العمارة الإسلامية والأندلسية في تلمسان.',
                  'Mosquée historique reflétant la splendeur de l\'architecture islamique et andalouse à Tlemcen.',
                  'Historic mosque reflecting the splendor of Islamic and Andalusian architecture in Tlemcen.'),
    'mausoleum': ('ضريح ومزار ديني من معالم التراث الروحي لمدينة تلمسان.',
                  'Mausolée et sanctuaire religieux, haut lieu du patrimoine spirituel de Tlemcen.',
                  'Mausoleum and religious shrine, a landmark of Tlemcen\'s spiritual heritage.'),
    'school':    ('مدرسة دينية تاريخية تجسّد دور تلمسان في نشر العلم والحضارة الإسلامية.',
                  'École coranique historique incarnant le rôle de Tlemcen dans la diffusion du savoir islamique.',
                  'Historic religious school embodying Tlemcen\'s role in spreading Islamic knowledge.'),
    'civil':     ('معلم من معالم العمارة المدنية في المدينة القديمة لتلمسان.',
                  'Monument de l\'architecture civile dans la vieille ville de Tlemcen.',
                  'Monument of civil architecture in the old city of Tlemcen.'),
    'military':  ('معلم من معالم العمارة العسكرية الزيانية يشهد على منعة المدينة القديمة.',
                  'Monument de l\'architecture militaire ziyanide témoignant de la résistance de la vieille ville.',
                  'Ziyanid military architecture monument testifying to the resilience of the old city.'),
}

HISTORY = {
    'geo':       ('هذا الموقع جزء من التراث الأثري والجغرافي لتلمسان التي شهدت حضارات متعاقبة منذ العصور القديمة.',
                  'Ce site fait partie du patrimoine archéologique et géographique de Tlemcen, qui a connu des civilisations successives depuis l\'Antiquité.',
                  'This site is part of the archaeological and geographical heritage of Tlemcen, which witnessed successive civilizations since ancient times.'),
    'mosque':    ('بُنيت هذه المساجد في عهد الدولة الزيانية وما سبقها من حضارات إسلامية، وتُعدّ شواهد على ازدهار تلمسان في العصور الوسطى.',
                  'Ces mosquées furent construites à l\'époque de la dynastie ziyanide et des civilisations islamiques antérieures, témoignant de la prospérité de Tlemcen au Moyen Âge.',
                  'These mosques were built during the Ziyanid dynasty and earlier Islamic civilizations, bearing witness to Tlemcen\'s prosperity in the Middle Ages.'),
    'mausoleum': ('تُعدّ أضرحة تلمسان من أبرز مواقع التراث الروحي في شمال أفريقيا، حيث دُفن فيها كبار العلماء والأولياء الصالحين.',
                  'Les mausolées de Tlemcen figurent parmi les sites du patrimoine spirituel les plus importants d\'Afrique du Nord, où reposent de grands savants et saints hommes.',
                  'The mausoleums of Tlemcen are among the most significant spiritual heritage sites in North Africa, where great scholars and saints are buried.'),
    'school':    ('ارتبطت مدارس تلمسان الدينية باسم المدينة العلمية والثقافية التي كانت قِبلة طلاب العلم من أرجاء المغرب الإسلامي.',
                  'Les écoles religieuses de Tlemcen étaient liées à la réputation scientifique et culturelle de la ville, qui accueillait des étudiants de tout le Maghreb islamique.',
                  'Tlemcen\'s religious schools were linked to the city\'s scientific and cultural reputation, attracting students from across the Islamic Maghreb.'),
    'civil':     ('تعكس هذه المعالم المدنية التنوع المعماري لمدينة تلمسان التي جمعت بين الفن الإسلامي والأندلسي والمغربي في عمارتها الحضرية.',
                  'Ces monuments civils reflètent la diversité architecturale de Tlemcen, qui a combiné les arts islamique, andalou et maghrébin dans son architecture urbaine.',
                  'These civil monuments reflect the architectural diversity of Tlemcen, which combined Islamic, Andalusian, and Maghrebi arts in its urban architecture.'),
    'military':  ('شيّد الزيانيون منظومة دفاعية متكاملة لحماية مدينة تلمسان، تشمل الأسوار والأبراج والأبواب والقلاع التي لا تزال بعض أجزائها قائمة.',
                  'Les Ziyanides ont construit un système défensif intégré pour protéger la ville de Tlemcen, comprenant des remparts, des tours, des portes et des forteresses.',
                  'The Ziyanids built an integrated defense system to protect Tlemcen, including walls, towers, gates, and fortresses, some of which still stand today.'),
}

# ── All 168 places: (num, cat_type, name_ar, name_fr, name_en, map_url) ──────
PLACES = [
    # General archaeological / geographic zones (1–12)
    (1,  'geo',       'مدينة تلمسان',                          'Tlemcen',                                        'Tlemcen',                                            'https://www.google.com/maps/@34.881800,-1.316700,20z'),
    (2,  'geo',       'هضبة لالة ستي',                         'Plateau de Lalla Setti',                         'Plateau of Lalla Setti',                             'https://www.google.com/maps/@34.868130,-1.318770,20z'),
    (3,  'geo',       'أقادير / بوماريا',                      'Agadir / Boumaria',                              'Agadir / Boumaria',                                  'https://www.google.com/maps/@34.888200,-1.301580,20z'),
    (4,  'geo',       'تاغرارت',                               'Tagrart',                                        'Tagrart',                                            'https://www.google.com/maps/@34.883771,-1.310485,20z'),
    (5,  'geo',       'المنصورة',                              'Mansourah',                                      'Mansourah',                                          'https://www.google.com/maps/@34.873300,-1.330300,20z'),
    (6,  'geo',       'العباد',                                'El Eubbad',                                      'El Eubbad',                                          'https://www.google.com/maps/@34.877600,-1.290170,20z'),
    (7,  'geo',       'سيدي الحلوي',                           'Sidi El Haloui',                                 'Sidi El Haloui',                                     'https://www.google.com/maps/@34.888030,-1.307930,20z'),
    (8,  'geo',       'بودغن',                                 'Boudghene',                                      'Boudghene',                                          'https://www.google.com/maps/@34.871470,-1.317850,20z'),
    (9,  'geo',       'شتوان',                                 'Chetouane',                                      'Chetouane',                                          'https://www.google.com/maps/@34.921290,-1.295120,20z'),
    (10, 'geo',       'سيدي سعيد',                             'Sidi Said',                                      'Sidi Said',                                          'https://www.google.com/maps/@34.890000,-1.314210,20z'),
    (11, 'geo',       'وادي الصفصيف',                          'Oued es Safsaf',                                 'Oued es Safsaf',                                     'https://www.google.com/maps/@34.933330,-1.300000,20z'),
    (12, 'geo',       'وادي مشتكانة',                          'Oued Meshkana',                                  'Wadi Meshkana',                                      'https://www.google.com/maps/@34.886500,-1.296900,20z'),
    # Religious architecture - mosques (13–41)
    (13, 'mosque',    'جامع أقادير',                           'Mosquée d\'Agadir',                              'Agadir Mosque',                                      'https://www.google.com/maps/@34.889430,-1.300100,20z'),
    (14, 'mosque',    'جامع سيدي الحلوي',                      'Mosquée Sidi El Haloui',                         'Sidi El Haloui Mosque',                              'https://www.google.com/maps/@34.888030,-1.307930,20z'),
    (15, 'mosque',    'مسجد سيدي الجبار',                      'Mosquée Sidi Eldjebbar',                         'Sidi Eldjebbar Mosque',                              'https://www.google.com/maps/@34.886340,-1.308520,20z'),
    (16, 'mosque',    'مسجد سيدي اليدون',                      'Mosquée Sidi El Yeddoun',                        'Sidi El Yeddoun Mosque',                             'https://www.google.com/maps/@34.885700,-1.309280,20z'),
    (17, 'mosque',    'مسجد سيدي بلحسن الراشيدي',              'Mosquée de Sidi Bellahsen',                      'Sidi Bellahsen Mosque',                              'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    (18, 'mosque',    'مسجد باب زيري',                         'Mosquée Bab Zir',                                'Bab Zir Mosque',                                     'https://www.google.com/maps/@34.886420,-1.306730,20z'),
    (19, 'mosque',    'مسجد الشرفاء',                          'Mosquée des Chorfas',                            'Mosque of the Chorfas',                              'https://www.google.com/maps/@34.885080,-1.308490,20z'),
    (20, 'mosque',    'مسجد لالة الغريبة',                     'Mosquée Lalla Gheriba',                          'Lalla Gheriba Mosque',                               'https://www.google.com/maps/@34.885250,-1.307790,20z'),
    (21, 'mosque',    'مسجد سيدي البناء',                      'Mosquée Sidi Benna',                             'Sidi Benna Mosque',                                  'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (22, 'mosque',    'الجامع الكبير',                         'Grande Mosquée de Tlemcen',                      'Grand Mosque of Tlemcen',                            'https://www.google.com/maps/@34.883771,-1.310485,20z'),
    (23, 'mosque',    'مسجد الشيخ السنوسي',                    'Mosquée Sidi Snouci',                            'Sidi Snouci Mosque',                                 'https://www.google.com/maps/@34.884690,-1.307840,20z'),
    (24, 'mosque',    'مسجد سيدي زايد',                        'Mosquée Sidi Zaid',                              'Sidi Zaid Mosque',                                   'https://www.google.com/maps/@34.881500,-1.314200,20z'),
    (25, 'mosque',    'مسجد سيدي أبي الحسن التنسي',            'Mosquée Sidi Abu al-Hasan Et-Tensi',             'Sidi Abu al-Hasan Et-Tensi Mosque',                  'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    (26, 'mosque',    'مسجد لالة الرؤية',                      'Mosquée Lalla Reya',                             'Lalla Reya Mosque',                                  'https://www.google.com/maps/@34.883900,-1.307030,20z'),
    (27, 'mosque',    'مسجد سيدي القلعي',                      'Mosquée Sidi El Kalai',                          'Sidi El Kalai Mosque',                               'https://www.google.com/maps/@34.883890,-1.306320,20z'),
    (28, 'mosque',    'مسجد ابن مرزوق الكفيف',                 'Mosquée Ibn Marzouq El Kafif',                   'Ibn Marzouq El Kafif Mosque',                        'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (29, 'mosque',    'مسجد لالة المرفودة',                    'Mosquée Lalla El Marfouda',                      'Lalla El Marfouda Mosque',                           'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (30, 'mosque',    'مسجد سيدي حامد',                        'Mosquée Sidi Hamed',                             'Sidi Hamed Mosque',                                  'https://www.google.com/maps/@34.881700,-1.312050,20z'),
    (31, 'mosque',    'مسجد أولاد الإمام',                     'Mosquée Ouled el-Imam',                          'Ouled el-Imam Mosque',                               'https://www.google.com/maps/@34.881270,-1.313350,20z'),
    (32, 'mosque',    'مسجد سيدي إبراهيم المصمودي',            'Mosquée Sidi Brahim El Masmoudi',                'Sidi Brahim El Masmoudi Mosque',                     'https://www.google.com/maps/@34.881590,-1.311310,20z'),
    (33, 'mosque',    'مسجد أبو عبد الله الشريف التلمساني',    'Mosquée Abou Abdellah El Charif',                'Abou Abdellah El Charif Mosque',                     'https://www.google.com/maps/@34.879100,-1.310800,20z'),
    (34, 'mosque',    'مسجد سيدي إبراهيم الغريب',              'Mosquée Sidi Brahim El Gharib',                  'Sidi Brahim El Gharib Mosque',                       'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (35, 'mosque',    'مسجد سيدي الوزان',                      'Mosquée Sidi Ouazzen',                           'Sidi Ouazzen Mosque',                                'https://www.google.com/maps/@34.882110,-1.306070,20z'),
    (36, 'mosque',    'مسجد المشور',                           'Mosquée El Mechouar',                            'El Mechouar Mosque',                                 'https://www.google.com/maps/@34.880480,-1.309430,20z'),
    (37, 'mosque',    'مسجد سيدي الزكري',                      'Mosquée Sidi Ez-Zakri',                          'Sidi Ez-Zakri Mosque',                               'https://www.google.com/maps/@34.879100,-1.310800,20z'),
    (38, 'mosque',    'مئذنة المنصورة',                         'Minaret de Mansourah (ruines)',                  'Mansourah Minaret (ruins)',                           'https://www.google.com/maps/@34.870810,-1.338590,20z'),
    (39, 'mosque',    'مصلى بودغن',                            'Oratoire de Boudghene',                          'Boudghene Oratory',                                  'https://www.google.com/maps/@34.871470,-1.317850,20z'),
    (40, 'mosque',    'مئذنة سيدي إسحاق الطيار',               'Minaret Sidi Ishaq al-Tayyar',                   'Sidi Ishaq al-Tayyar Minaret',                       'https://www.google.com/maps/@34.879710,-1.293990,20z'),
    (41, 'mosque',    'جامع سيدي أبي مدين',                    'Mosquée Sidi Boumediene',                        'Sidi Boumediene Mosque',                             'https://www.google.com/maps/@34.877830,-1.289560,20z'),
    # Religious architecture - mausoleums, graves, cemeteries (42–78)
    (42, 'mausoleum', 'ضريح سيدي الداودي',                     'Mausolée de Sidi Daoudi',                        'Sidi Daoudi Mausoleum',                              'https://www.google.com/maps/@34.890050,-1.297920,20z'),
    (43, 'mausoleum', 'ضريح سيدي وهب',                         'Mausolée de Sidi Wahab',                         'Sidi Wahab Mausoleum',                               'https://www.google.com/maps/@34.886630,-1.298730,20z'),
    (44, 'mausoleum', 'ضريح سيدي يعقوب التفريسي',              'Mausolée de Sidi Yaqub',                         'Sidi Yaqub Mausoleum',                               'https://www.google.com/maps/@34.885710,-1.298630,20z'),
    (45, 'mausoleum', 'قبة بنت السلطان',                       'Coupole de la Fille du Sultan',                  'Dome of the Sultan\'s Daughter',                     'https://www.google.com/maps/@34.885710,-1.298630,20z'),
    (46, 'mausoleum', 'ضريح الخليفة',                          'Mausolée du Calife',                             'Mausoleum of the Caliph',                            'https://www.google.com/maps/@34.885710,-1.298630,20z'),
    (47, 'mausoleum', 'ضريح سيدي الحلوي الشوذي',               'Mausolée Sidi El Haloui',                        'Sidi El Haloui Mausoleum',                           'https://www.google.com/maps/@34.888030,-1.307930,20z'),
    (48, 'mausoleum', 'مزار سيدي الحلوي الشوذي',               'Sanctuaire Sidi El Haloui',                      'Sidi El Haloui Shrine',                              'https://www.google.com/maps/@34.888030,-1.307930,20z'),
    (49, 'mausoleum', 'ضريح سيدي أبي الحسن الراشيدي',          'Mausolée Sidi Bellahsen',                        'Sidi Bellahsen Mausoleum',                           'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    (50, 'mausoleum', 'قبر سيدي البرادعي',                     'Tombe Sidi El Bradai',                           'Sidi El Bradai Tomb',                                'https://www.google.com/maps/@34.886000,-1.315350,20z'),
    (51, 'mausoleum', 'ضريح سيدي الحباك',                      'Mausolée Sidi El Habbak',                        'Sidi El Habbak Mausoleum',                           'https://www.google.com/maps/@34.882050,-1.306650,20z'),
    (52, 'mausoleum', 'ضريح سيدي واضح',                        'Mausolée Sidi Wadih',                            'Sidi Wadih Mausoleum',                               'https://www.google.com/maps/@34.886000,-1.315350,20z'),
    (53, 'mausoleum', 'ضريح سيدي سعد',                         'Mausolée Sidi Saad',                             'Sidi Saad Mausoleum',                                'https://www.google.com/maps/@34.883200,-1.311050,20z'),
    (54, 'mausoleum', 'قبر مولاي يعقوب',                       'Tombe Moulay Yacoub',                            'Moulay Yacoub Tomb',                                 'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (55, 'mausoleum', 'ضريح سيدي بلحسن الغوماري',              'Mausolée Sidi Bellahsen El Ghoumari',            'Sidi Bellahsen El Ghoumari Mausoleum',               'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    (56, 'mausoleum', 'ضريح ابن مرزوق الحفيد',                 'Mausolée Ibn Marzouq El Hafid',                  'Ibn Marzouq El Hafid Mausoleum',                     'https://www.google.com/maps/@34.883771,-1.310485,20z'),
    (57, 'mausoleum', 'قبر سيدي شقرون',                        'Tombe Sidi Chokroun',                            'Sidi Chokroun Tomb',                                 'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (58, 'mausoleum', 'مزار سيدي المزوني',                     'Sanctuaire Sidi El Mazouani',                    'Sidi El Mazouani Shrine',                            'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (59, 'mausoleum', 'ضريح سيدي براهيم المصمودي',             'Mausolée Sidi Brahim El Masmoudi',               'Sidi Brahim El Masmoudi Mausoleum',                  'https://www.google.com/maps/@34.881590,-1.311310,20z'),
    (60, 'mausoleum', 'ضريح سيدي محمد بوطباق',                 'Mausolée Sidi Mohammed Boutbak',                 'Sidi Mohammed Boutbak Mausoleum',                    'https://www.google.com/maps/@34.877950,-1.289770,20z'),
    (61, 'mausoleum', 'ضريح سيدي معمر بن عالية',               'Mausolée Sidi Maamer Ben Alia',                  'Sidi Maamer Ben Alia Mausoleum',                     'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    (62, 'mausoleum', 'ضريح سيدي بوجمعة الكواش',               'Mausolée Sidi Boujemaa El Kouach',               'Sidi Boujemaa El Kouach Mausoleum',                  'https://www.google.com/maps/@34.876900,-1.301700,20z'),
    (63, 'mausoleum', 'قبة باب سفير',                          'Coupole de Bab Sefir',                           'Bab Sefir Dome',                                     'https://www.google.com/maps/@34.876900,-1.301700,20z'),
    (64, 'mausoleum', 'ضريح سيدي علي بن غيم',                  'Mausolée Sidi Ali Ben Gheim',                    'Sidi Ali Ben Gheim Mausoleum',                       'https://www.google.com/maps/@34.877600,-1.290170,20z'),
    (65, 'mausoleum', 'ضريح سيدي إسحاق الطيار',                'Mausolée Sidi Ishaq al-Tayyar',                  'Sidi Ishaq al-Tayyar Mausoleum',                     'https://www.google.com/maps/@34.879710,-1.293990,20z'),
    (66, 'mausoleum', 'مقبرة الشيخ السنوسي',                   'Cimetière du Cheikh Senoussi',                   'Cheikh Senoussi Cemetery',                           'https://www.google.com/maps/@34.878600,-1.297410,20z'),
    (67, 'mausoleum', 'ضريح الشيخ السنوسي',                    'Mausolée Sidi Sinoussi',                         'Sidi Sinoussi Mausoleum',                            'https://www.google.com/maps/@34.878600,-1.297410,20z'),
    (68, 'mausoleum', 'ضريح سيدي علي بنابي عمر',               'Mausolée Sidi Ali Ben Abi Omar',                 'Sidi Ali Ben Abi Omar Mausoleum',                    'https://www.google.com/maps/@34.879710,-1.293990,20z'),
    (69, 'mausoleum', 'المقبرة المسيحية',                       'Cimetière Chrétien',                             'Christian Cemetery',                                 'https://www.google.com/maps/@34.874900,-1.309000,20z'),
    (70, 'mausoleum', 'قبتان مجهولتان',                        'Deux Coupoles Inconnues',                        'Two Unknown Domes',                                  'https://www.google.com/maps/@34.877600,-1.290170,20z'),
    (71, 'mausoleum', 'ضريح سيدي براهيم',                      'Mausolée Sidi Brahim',                           'Sidi Brahim Mausoleum',                              'https://www.google.com/maps/@34.877660,-1.289780,20z'),
    (72, 'mausoleum', 'ضريح سيدي العبادي',                     'Mausolée Sidi El Abbadi',                        'Sidi El Abbadi Mausoleum',                           'https://www.google.com/maps/@34.877600,-1.290170,20z'),
    (73, 'mausoleum', 'قبر سيدي زكريا',                        'Tombe Sidi Zakariya',                            'Sidi Zakariya Tomb',                                 'https://www.google.com/maps/@34.877600,-1.290170,20z'),
    (74, 'mausoleum', 'ضريح سيدي أبي مدين',                    'Mausolée de Sidi Boumediene',                    'Sidi Boumediene Mausoleum',                          'https://www.google.com/maps/@34.877950,-1.289770,20z'),
    (75, 'mausoleum', 'ضريح سيدي عبد القادر الجيلاني',          'Mausolée Sidi Abdelkader El Djilani',            'Sidi Abdelkader El Djilani Mausoleum',               'https://www.google.com/maps/@34.877950,-1.289770,20z'),
    (76, 'mausoleum', 'ضريح سيدي عبد الله بن علي البعل',       'Mausolée de Sidi Abdellah Lbaal',                'Sidi Abdellah Lbaal Mausoleum',                      'https://www.google.com/maps/@34.875430,-1.283040,20z'),
    (77, 'mausoleum', 'ضريح سيدي الطاهر',                      'Mausolée Sidi Et-Taher',                         'Sidi Et-Taher Mausoleum',                            'https://www.google.com/maps/@34.877600,-1.290170,20z'),
    (78, 'mausoleum', 'ضريح لالة ستي',                         'Mausolée de Lalla Setti',                        'Lalla Setti Mausoleum',                              'https://www.google.com/maps/@34.868130,-1.318770,20z'),
    # Religious architecture - schools / khalwa (79–82)
    (79, 'school',    'خلوة سيدي السنوسي',                     'Khalwa de Sidi Senoussi',                        'Sidi Senoussi Khalwa',                               'https://www.google.com/maps/@34.878600,-1.297410,20z'),
    (80, 'school',    'المدرسة الفرنسية',                       'Medersa Française',                              'French Medersa',                                     'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    (81, 'school',    'مدرسة أولاد الإمام',                     'Medersa Ouled el-Imam',                          'Ouled el-Imam Medersa',                              'https://www.google.com/maps/@34.881270,-1.313350,20z'),
    (82, 'school',    'مدرسة أبي الحسن المريني',                'Medersa Abou al-Hasan El Marinide',              'Abou al-Hasan El Marinide Medersa',                  'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    # Civil architecture - houses and palaces (83–92)
    (83, 'civil',     'منزل سيدي الحباك',                      'Demeure Sidi El Habbak',                         'Sidi El Habbak House',                               'https://www.google.com/maps/@34.882050,-1.306650,20z'),
    (84, 'civil',     'منزل مرابط',                            'Demeure Mrabat',                                 'Mrabat House',                                       'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (85, 'civil',     'منزل المقري',                           'Demeure El Makkari',                             'El Makkari House',                                   'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (86, 'civil',     'منزل محمد ديب',                         'Demeure Mohammed Dib',                           'Mohammed Dib House',                                 'https://www.google.com/maps/@34.880480,-1.309430,20z'),
    (87, 'civil',     'منزل بن عزوز',                          'Demeure Ben Azzouz',                             'Ben Azzouz House',                                   'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (88, 'civil',     'قصر المشور',                            'Palais El Mechouar',                             'El Mechouar Palace',                                 'https://www.google.com/maps/@34.880833,-1.308611,20z'),
    (89, 'civil',     'منزل الآغا',                            'Demeure de l\'Agha',                             'House of the Agha',                                  'https://www.google.com/maps/@34.880833,-1.308611,20z'),
    (90, 'civil',     'بيت الحجيج',                            'Maison des Pèlerins',                            'House of Pilgrims',                                  'https://www.google.com/maps/@34.877950,-1.289770,20z'),
    (91, 'civil',     'قصر السلطان',                           'Palais du Sultan',                               'Sultan\'s Palace',                                   'https://www.google.com/maps/@34.877890,-1.289680,20z'),
    (92, 'civil',     'منزل محبوبي',                           'Demeure Mahboubi',                               'Mahboubi House',                                     'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    # Civil architecture - funduqs / caravanserais (93–101)
    (93,  'civil',    'فندق ابن خلدون',                        'Fondouk Ibn Khaldoun',                           'Ibn Khaldoun Fondouk',                               'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (94,  'civil',    'فندق المدرس',                           'Fondouk El Mudarres',                            'El Mudarres Fondouk',                                'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (95,  'civil',    'فندق مامي',                             'Fondouk Mami',                                   'Mami Fondouk',                                       'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (96,  'civil',    'فندق بارا',                             'Fondouk Bara',                                   'Bara Fondouk',                                       'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (97,  'civil',    'فندق بوعلي',                            'Fondouk Bou Ali',                                'Bou Ali Fondouk',                                    'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (98,  'civil',    'فندق بن منصور',                         'Fondouk Ben Mansour',                            'Ben Mansour Fondouk',                                'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (99,  'civil',    'فندق رستان',                            'Fondouk Roustan',                                'Roustan Fondouk',                                    'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (100, 'civil',    'فندق الرمانة',                          'Fondouk Er-Rommana',                             'Er-Rommana Fondouk',                                 'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (101, 'civil',    'فندق شعلي',                             'Fondouk Chaali',                                 'Chaali Fondouk',                                     'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    # Civil architecture - hammams (102–114)
    (102, 'civil',    'حمام بنت السلطان',                      'Hammam de la Fille du Sultan',                   'Sultan\'s Daughter Hammam',                          'https://www.google.com/maps/@34.880833,-1.308611,20z'),
    (103, 'civil',    'حمام أقادير',                           'Hammam Agadir',                                  'Agadir Hammam',                                      'https://www.google.com/maps/@34.888200,-1.301580,20z'),
    (104, 'civil',    'حمام بن قطيطة',                         'Hammam Ben Outitta',                             'Ben Outitta Hammam',                                 'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (105, 'civil',    'حمام الحفرة',                           'Hammam El Hofra',                                'El Hofra Hammam',                                    'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (106, 'civil',    'حمام الصباغين',                         'Hammam des Teinturiers',                         'Dyers\' Hammam',                                     'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (107, 'civil',    'حمام العشعاشي',                         'Hammam El Achaachi',                             'El Achaachi Hammam',                                 'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (108, 'civil',    'حمام باب علي',                          'Hammam Bab Ali',                                 'Bab Ali Hammam',                                     'https://www.google.com/maps/@34.882050,-1.306650,20z'),
    (109, 'civil',    'حمام بن ويس',                           'Hammam Ben Ouais',                               'Ben Ouais Hammam',                                   'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (110, 'civil',    'حمام الربط',                            'Hammam Er-Ribat',                                'Er-Ribat Hammam',                                    'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (111, 'civil',    'حمام مولاي يعقوب',                      'Hammam Moulay Yacoub',                           'Moulay Yacoub Hammam',                               'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (112, 'civil',    'حمام سماعيل',                           'Hammam Ismail',                                  'Ismail Hammam',                                      'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (113, 'civil',    'حمام بن سليمان',                        'Hammam Ben Slimane',                             'Ben Slimane Hammam',                                 'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (114, 'civil',    'حمام العباد',                           'Hammam El-Eubbad',                               'El-Eubbad Hammam',                                   'https://www.google.com/maps/@34.877930,-1.289330,20z'),
    # Civil architecture - water points / fountains / cisterns (115–122)
    (115, 'civil',    'عين الدباغ',                            'Fontaine Ain Ed-Dabbagh',                        'Ain Ed-Dabbagh Fountain',                            'https://www.google.com/maps/@34.886000,-1.315350,20z'),
    (116, 'civil',    'سقاية سيدي الحلوي',                     'Sébil Sidi El Haloui',                           'Sidi El Haloui Water Point',                         'https://www.google.com/maps/@34.888030,-1.307930,20z'),
    (117, 'civil',    'بئر منزل الحباك',                       'Puits de la Demeure El Habbak',                  'El Habbak House Well',                               'https://www.google.com/maps/@34.882050,-1.306650,20z'),
    (118, 'civil',    'صهريج الكيفان',                         'Citerne du Kaïfan',                              'Kaïfan Cistern',                                     'https://www.google.com/maps/@34.876900,-1.301700,20z'),
    (119, 'civil',    'الصهريج الكبير',                        'La Grande Citerne',                              'The Great Cistern',                                  'https://www.google.com/maps/@34.876900,-1.301700,20z'),
    (120, 'civil',    'سقاية سيدي إسحاق الطيار',               'Sébil Sidi Ishaq al-Tayyar',                     'Sidi Ishaq al-Tayyar Water Point',                   'https://www.google.com/maps/@34.879710,-1.293990,20z'),
    (121, 'civil',    'سقاية سيدي أبي مدين',                   'Sébil Sidi Boumediene',                          'Sidi Boumediene Water Point',                        'https://www.google.com/maps/@34.877890,-1.289680,20z'),
    (122, 'civil',    'بئر سيدي أبي مدين',                     'Puits de Sidi Boumediene',                       'Sidi Boumediene Well',                               'https://www.google.com/maps/@34.877890,-1.289680,20z'),
    # Civil architecture - markets (123)
    (123, 'civil',    'القيسارية',                             'La Qissaria',                                    'The Qissaria',                                       'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    # Civil architecture - lanes / quarters (124–138)
    (124, 'civil',    'درب أبو عبد الله الشريف التلمساني',     'Derb Abou Abdellah El Charif',                   'Abou Abdellah El Charif Derb',                       'https://www.google.com/maps/@34.879100,-1.310800,20z'),
    (125, 'civil',    'درب سيدي حامد',                         'Derb Sidi Hamed',                                'Sidi Hamed Derb',                                    'https://www.google.com/maps/@34.881700,-1.312050,20z'),
    (126, 'civil',    'درب ابن مرزوق',                         'Derb Ibn Marzouq',                               'Ibn Marzouq Derb',                                   'https://www.google.com/maps/@34.884550,-1.309450,20z'),
    (127, 'civil',    'درب سيدي الزكري',                       'Derb Sidi Ez-Zakri',                             'Sidi Ez-Zakri Derb',                                 'https://www.google.com/maps/@34.879100,-1.310800,20z'),
    (128, 'civil',    'درب سيدي القاضي',                       'Derb Sidi El Qadi',                              'Sidi El Qadi Derb',                                  'https://www.google.com/maps/@34.882050,-1.306650,20z'),
    (129, 'civil',    'درب الصباغين',                          'Derb des Teinturiers',                           'Dyers\' Derb',                                       'https://www.google.com/maps/@34.882250,-1.306350,20z'),
    (130, 'civil',    'درب الصبانين',                          'Derb des Savonniers',                            'Soapmakers\' Derb',                                  'https://www.google.com/maps/@34.886340,-1.308520,20z'),
    (131, 'civil',    'درب مولاي الطيب',                       'Derb Moulay El Tayeb',                           'Moulay El Tayeb Derb',                               'https://www.google.com/maps/@34.884100,-1.310050,20z'),
    (132, 'civil',    'درب سيدي سعد',                          'Derb Sidi Saad',                                 'Sidi Saad Derb',                                     'https://www.google.com/maps/@34.883200,-1.311050,20z'),
    (133, 'civil',    'درب أولاد الإمام',                      'Derb Ouled el-Imam',                             'Ouled el-Imam Derb',                                 'https://www.google.com/maps/@34.881270,-1.313350,20z'),
    (134, 'civil',    'درب دار الضياف',                        'Derb Dar Eddiyaf',                               'Dar Eddiyaf Derb',                                   'https://www.google.com/maps/@34.879100,-1.310800,20z'),
    (135, 'civil',    'درب الحجامين',                          'Derb des Barbiers',                              'Barbers\' Derb',                                     'https://www.google.com/maps/@34.881500,-1.314200,20z'),
    (136, 'civil',    'درب الموحدين',                          'Derb des Almohades',                             'Almohades Derb',                                     'https://www.google.com/maps/@34.883700,-1.307250,20z'),
    (137, 'civil',    'درب مسوفة',                             'Derb Messoufah',                                 'Messoufah Derb',                                     'https://www.google.com/maps/@34.884680,-1.307840,20z'),
    (138, 'civil',    'درب سبعة أقواس',                        'Derb des Sept Arches',                           'Seven Arches Derb',                                  'https://www.google.com/maps/@34.882778,-1.311111,20z'),
    # Civil architecture - ovens (139–145)
    (139, 'civil',    'فران حارة الرمى',                       'Four de Hara Er-Rami',                           'Er-Rami Quarter Oven',                               'https://www.google.com/maps/@34.883700,-1.307250,20z'),
    (140, 'civil',    'فران أقادير',                           'Four Agadir',                                    'Agadir Oven',                                        'https://www.google.com/maps/@34.888200,-1.301580,20z'),
    (141, 'civil',    'فران سيدي الجبار',                      'Four Sidi Eldjebbar',                            'Sidi Eldjebbar Oven',                                'https://www.google.com/maps/@34.886340,-1.308520,20z'),
    (142, 'civil',    'فران بن جملة',                          'Four Ben Djemla',                                'Ben Djemla Oven',                                    'https://www.google.com/maps/@34.881500,-1.314200,20z'),
    (143, 'civil',    'فران العبد',                            'Four El Abd',                                    'El Abd Oven',                                        'https://www.google.com/maps/@34.881270,-1.313350,20z'),
    (144, 'civil',    'فران باب الحديد',                       'Four Bab El Hadid',                              'Bab El Hadid Oven',                                  'https://www.google.com/maps/@34.878830,-1.310930,20z'),
    (145, 'civil',    'فران بن سلكة',                          'Four Ben Selka',                                 'Ben Selka Oven',                                     'https://www.google.com/maps/@34.881500,-1.314200,20z'),
    # Military architecture - walls (146–151)
    (146, 'military', 'السور الشمالي الشرقي من مدينة أقادير',  'Remparts nord-est d\'Agadir',                    'North-East Walls of Agadir',                         'https://www.google.com/maps/@34.889200,-1.304150,20z'),
    (147, 'military', 'الأسوار الجنوبية من مدينة تاغرارت',     'Remparts sud de Tagrart',                        'Southern Walls of Tagrart',                          'https://www.google.com/maps/@34.877800,-1.310000,20z'),
    (148, 'military', 'السور الشرقي من مدينة تاغرارت',         'Rempart est de Tagrart',                         'Eastern Wall of Tagrart',                            'https://www.google.com/maps/@34.884000,-1.305700,20z'),
    (149, 'military', 'السور الغربي من مدينة تاغرارت',         'Rempart ouest de Tagrart',                       'Western Wall of Tagrart',                            'https://www.google.com/maps/@34.881400,-1.316000,20z'),
    (150, 'military', 'أسوار بالجهة الجنوبية من مدينة تاغرارت','Remparts sud de Tagrart (section)',               'Southern Tagrart Walls (section)',                   'https://www.google.com/maps/@34.877800,-1.310000,20z'),
    (151, 'military', 'أسوار المنصورة',                        'Remparts de Mansourah',                          'Mansourah Walls',                                    'https://www.google.com/maps/@34.870810,-1.338590,20z'),
    # Military architecture - towers / trenches (152–160)
    (152, 'military', 'الأبراج الشمالية الشرقية لمدينة أقادير', 'Tours nord-est d\'Agadir',                      'North-East Towers of Agadir',                        'https://www.google.com/maps/@34.889430,-1.300100,20z'),
    (153, 'military', 'برج باب الحمام - أقادير',               'Tour Bab El Hammam – Agadir',                    'Bab El Hammam Tower – Agadir',                       'https://www.google.com/maps/@34.887900,-1.298400,20z'),
    (154, 'military', 'البرج المشرف على وادي مشتكانة من الناحية الشرقية', 'Tour dominant l\'oued Meshkana (est)', 'Tower Overlooking Wadi Meshkana (east)',              'https://www.google.com/maps/@34.887200,-1.296500,20z'),
    (155, 'military', 'البرج الغربي من مدينة أقادير',           'Tour ouest d\'Agadir',                           'Western Tower of Agadir',                            'https://www.google.com/maps/@34.888300,-1.303300,20z'),
    (156, 'military', 'الأبراج الجنوبية الشرقية من مدينة تاغرارت','Tours sud-est de Tagrart',                    'South-East Towers of Tagrart',                       'https://www.google.com/maps/@34.878800,-1.305300,20z'),
    (157, 'military', 'برج باب الحديد',                        'Tour Bab El Hadid',                              'Bab El Hadid Tower',                                 'https://www.google.com/maps/@34.878830,-1.310930,20z'),
    (158, 'military', 'برج الصفارين',                          'Tour des Chaudronniers',                         'Smelters\' Tower',                                   'https://www.google.com/maps/@34.879100,-1.310800,20z'),
    (159, 'military', 'أبراج المنصورة',                        'Tours de Mansourah',                             'Towers of Mansourah',                                'https://www.google.com/maps/@34.870810,-1.338590,20z'),
    (160, 'military', 'الخنادق',                               'Les Fossés',                                     'The Trenches',                                       'https://www.google.com/maps/@34.870810,-1.338590,20z'),
    # Military architecture - gates (161–166)
    (161, 'military', 'باب القرمادين',                         'Bab El Kermadine',                               'Bab El Kermadine Gate',                              'https://www.google.com/maps/@34.886340,-1.316460,20z'),
    (162, 'military', 'باب الخميس',                            'Bab El Khemis',                                  'Bab El Khemis Gate',                                 'https://www.google.com/maps/@34.874080,-1.324840,20z'),
    (163, 'military', 'باب الخوخة',                            'Bab El Khouakha',                                'Bab El Khouakha Gate',                               'https://www.google.com/maps/@34.886420,-1.306730,20z'),
    (164, 'military', 'باب الرواح',                            'Bab El Rouah',                                   'Bab El Rouah Gate',                                  'https://www.google.com/maps/@34.889200,-1.304150,20z'),
    (165, 'military', 'باب الحديد',                            'Bab El Hadid',                                   'Bab El Hadid Gate',                                  'https://www.google.com/maps/@34.878830,-1.310930,20z'),
    (166, 'military', 'باب التويتة',                           'Bab Touita',                                     'Bab Touita Gate',                                    'https://www.google.com/maps/@34.879900,-1.309250,20z'),
    # Military architecture - fortresses / castles (167–168)
    (167, 'military', 'قلعة المشور',                           'Château El Mechouar',                            'El Mechouar Castle',                                 'https://www.google.com/maps/@34.880833,-1.308611,20z'),
    (168, 'military', 'قلعة ابن الجاهل',                       'Château Ibn El Jahel',                           'Ibn El Jahel Castle',                                'https://www.google.com/maps/@34.877400,-1.304700,20z'),
]

# ── Visit duration defaults ───────────────────────────────────────────────────
VISIT = {
    'geo':       ('30 دق',   '30 min',   '30 min'),
    'mosque':    ('30 دق',   '30 min',   '30 min'),
    'mausoleum': ('20 دق',   '20 min',   '20 min'),
    'school':    ('30 دق',   '30 min',   '30 min'),
    'civil':     ('20 دق',   '20 min',   '20 min'),
    'military':  ('20 دق',   '20 min',   '20 min'),
}


def seed():
    with app.app_context():
        print(f'Clearing existing places...')
        PlaceTranslation.query.delete()
        Place.query.delete()
        db.session.commit()

        print(f'Inserting {len(PLACES)} places...')
        for num, cat, name_ar, name_fr, name_en, map_url in PLACES:
            # Use fetched image if available, otherwise fall back to category default
            photo = PLACE_PHOTOS.get(num) or PHOTO.get(cat, PHOTO['civil'])

            place = Place(
                photo_url=photo,
                emoji='🕌' if cat == 'mosque' else ('🏺' if cat == 'mausoleum' else ('📚' if cat == 'school' else ('🏛️' if cat == 'civil' else ('🏰' if cat == 'military' else '📍')))),
                categories=CATS[cat],
                rating='★★★★☆',
                map_url=map_url,
                qr_code=None,
                image_source='Wikimedia Commons – Public Domain',
                image_source_url='https://commons.wikimedia.org',
                info_source='جرد المعالم التاريخية و المواقع الأثرية لمدينة تلمسان',
            )
            db.session.add(place)
            db.session.flush()

            badge_ar, badge_fr, badge_en = BADGE[cat]
            desc_ar, desc_fr, desc_en = DESC[cat]
            hist_ar, hist_fr, hist_en = HISTORY[cat]
            vis_ar, vis_fr, vis_en = VISIT[cat]

            for lang, name, badge, desc, hist, vis in [
                ('ar', name_ar, badge_ar, desc_ar, hist_ar, vis_ar),
                ('fr', name_fr, badge_fr, desc_fr, hist_fr, vis_fr),
                ('en', name_en, badge_en, desc_en, hist_en, vis_en),
            ]:
                db.session.add(PlaceTranslation(
                    place_id=place.id,
                    lang=lang,
                    name=name,
                    badge=badge,
                    description=desc,
                    history=hist,
                    visit_duration=vis,
                ))

        db.session.commit()
        print(f'Done. {len(PLACES)} places inserted.')


if __name__ == '__main__':
    seed()
